version: '3'

services:
  db:
    container_name: ai-saas-db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: ai-saas
    ports:
      - 5432:5432
    volumes:
      - ./data/db:/var/lib/postgresql/data

  adminer:
    container_name: ai-saas-adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080
